// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Tag struct {
	ID   int32
	Name string
}

type Task struct {
	ID             int32
	Title          string
	TaskTime       time.Time
	TaskFinishDate time.Time
	UserID         int32
}

type TaskTag struct {
	TaskID int32
	TagID  int32
}

type User struct {
	ID    int32
	Uid   string
	Name  string
	Email string
}
